import type { Metadata } from "next";
import { Ledger } from "next/font/google";
import "./globals.css";

const ledger = Ledger({
  weight:'400',
  subsets: ['latin'],
  display: 'swap'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ledger.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
